Revert commit that removed Russian providers
opentofu/registry pull request #824
Opened 2024-08-28 13:27 UTC by JustMarfix

# Explanation

Yesterday, pull request #817 was successfully approved and merged into the main branch. As part of this pull request, all providers affiliated with or based in Russia were removed from the project's repository.

To explain this change, @cam72cam [provided](https://github.com/opentofu/registry/pull/817#issuecomment-2314944090) two links: [README.md](https://github.com/opentofu/opentofu/blob/main/README.md#registry-access) and [TSC_SUMMARY.md](https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access).

Additionally, as part of the discussion in issue #823, @DicsyDel [provided](https://github.com/opentofu/registry/issues/823#issuecomment-2314320206) information that "it was deemed appropriate to block access from certain territories to avoid any legal issues", citing sanctions on a [Russian legal entity](https://sanctionssearch.ofac.treas.gov/Details.aspx?id=18715).

# Why this decision is absolutely wrong and the arguments in its favor do not confirm its correctness

1. README.md, as well as TSC_SUMMARY.md, mention only the restriction on access from Russian IPs to the registry, but not the removal of Russian-related providers from the registry.
2. [Here](https://ofac.treasury.gov/faqs/1186), the U.S. Treasury Office of Foreign Assets Control explains how the restriction on the provision of information technology to Russia should be interpreted. The presence of files from Russian providers in the registry clearly does not fall under these interpretation.
3. [Here](https://ofac.treasury.gov/faqs/1188), the U.S. Treasury Office of Foreign Assets Control explains the nuances of providing information technology to companies affiliated with Russian companies. In particular, Yandex LLC, whose provider was removed from the register, has a subsidiary in Kazakhstan that uses the same provider, which makes it absolutely wrong to exclude the Yandex LLC provider from the register due to US sanctions.

# What should be done

The restriction on access to the registry from Russian IP addresses is absolutely justified by the need to comply with US sanctions. However, the removal of Russian-linked providers has nothing to do with compliance with sanctions, which I explained above.

Therefore, these providers should be returned to the registry. I kindly ask you not to close this PR without a full explanation of the reason for such deletion, as well as an answer to my counterarguments. After all, this is an open source, and the community would like to get a good explanation of what happened.

2024-08-28 14:40 UTC, MikhailAseev commented
In addition to the above mentioned

OpenTofu is an open source project published under Mozilla Public License and maintained by Linux Foundation.
Linux Foundation itself has this [page](https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects) where the following is stated:

> **What kind of open source projects are not subject to the EAR and export restrictions?**
>
> All of them. Open source software from the Linux Foundation and project communities we work with is published and made available to the public without restrictions on further dissemination or distribution of the software.
The following typical scenarios (but not an exhaustive list) are not subject to the EAR because “open source” is “published”:
> - Open source software that is published publicly is not subject to the EAR
> - Open source specifications that are published publicly are not subject to the EAR
> - Open source files that describe the designs for hardware that are published publicly are not subject to the EAR
> - Open source software binaries that are published publicly are not subject to the EAR
>
> To meet the requirement of “published” under the EAR, however, open source communities may need to take an additional step if the project includes encryption technology.

So, open source projects that are initially published under public licenses cannot be under export controls of the US and EU. This is stated on the official Linux Foundation website.

In this particular case, @ollevche (who is the original author of that PR) and @cam72cam (who approved that PR and merged it) are abusing their positions as the core devs of OpenTofu project.

2024-08-28 18:21 UTC, evilgn0me commented
Looking at this bs, I'm glad that I'm using "closed" Terraform.

2024-08-28 18:49 UTC, socketpair commented
I think that open source is not a place for politics. For what purpose would you remove something related to Russia? For what? Please, don't do bad things to Russian programmers, we are not to blame for what is happening. We help open source just like you help us all.

2024-08-28 19:59 UTC, kvendingoldo commented
The most interesting question: “why only Russia?”; why, for example, not Iran?

open source in now the place for politics.

2024-08-28 20:01 UTC, dmchmk commented
> why, for example, not Iran?

*cough*Is*cough*rael*cough*

2024-08-28 20:02 UTC, 097115 commented
> Please, don't do bad things to Russian programmers, we are not to blame for what is happening.

Russian programmers are not to blame for spyware? Bots? Attacks on critical infrastructure all around the world we hear on a daily basis? 

Then who are? Martians?

I suggest you to stop playing [your famous victim card](https://twitter.com/TimothyDSnyder/status/1636031399336583174?lang=en) at last and to start looking in the mirror.

2024-08-28 20:06 UTC, JustMarfix commented
Please stop discussing politics in this PR. There are separate forums for this.
The purpose of this PR is to return incorrectly deleted files back to the registry, and not to start a debate about whether Russian programmers are to blame for the actions of Russian hackers. Thank you.

2024-08-28 20:07 UTC, JoeMcNuggets commented
@097115, don't want to dissapoint you, but [there are another cybercrime threat sources](https://www.ox.ac.uk/news/2024-04-10-world-first-cybercrime-index-ranks-countries-cybercrime-threat-level).

2024-08-28 20:08 UTC, peter-volkov commented
> Russian programmers are not to blame for spyware? Bots? Attacks on critical infrastructure all around the world we hear on a daily basis?

Wow. Just wow. Do you know who else once were blaming a big group of people by nationality, citng some sprecific and hardly credible crimes?

2024-08-28 20:09 UTC, JustMarfix commented
Please just stop. Let's wait for the maintainer's response.

2024-08-28 20:13 UTC, 097115 commented
@peter-volkov 

...And here goes another day Russians compare themselves to Holocaust victims :))

Except, sorry to disappoint, you are exactly the other side in this example. So face the consequences.

2024-08-28 20:20 UTC, chamilad commented
> Wow. Just wow. Do you know who else once were blaming a big group of people by nationality, citng some specific and hardly credible crimes?

I hope you're joking. 

Unrelated note, why are all users who think "politics" is some disconnected aspect of life doing malware related projects on Github?

2024-08-28 21:01 UTC, mrdumpty commented
@097115 If youг disgusting behavior persists, then YOU will face the consequences from which the world will tremble. Russians are very patient people but all patience comes to an end.

I hope you all come to your senses. Burned in nuclear war do not need opentofu.

2024-08-28 22:48 UTC, slayer commented
The decision was absolutely right and totally understandable

2024-08-29 01:27 UTC, nepridumalnik commented
It's fascinating to see how easily the concept of openness and freedom in open source becomes selective. If tomorrow someone decides that developers from another country suddenly become inconvenient, will we continue to restrict access? Or perhaps we'll just forget that the foundation of open source is the exchange of knowledge without borders and discrimination? Maybe it's time to reflect on how far we're willing to go before turning free software into an exclusive club.

2024-08-29 01:49 UTC, Solpio commented
Zа ДуроVa

2024-08-29 02:12 UTC, aeiouaeiouaeiouaeiouaeiouaeiou approved these changes

2024-08-29 03:54 UTC, rowaasr13 commented
> @peter-volkov
> ...And here goes another day Russians once again compare themselves to Holocaust victims :))

You DO realize that 20m of Russian civilian population were murdered in that WW2 thing, do you?
Overwhelmingly by several European countries that pretend to be pinnacles of democratic virtues today. While backing same Banderites as 80 years ago and attacking Russia once again, no less.

Please disappear and take your narratives with you.

2024-08-29 04:27 UTC, IvanKirpichnikov commented
let's better restrict your access to open source

2024-08-29 04:27 UTC, ixth commented
@rowaasr13 
> same Banderites as 80 years ago
You're just supporting this discourse and making things justifiable.

2024-08-29 04:30 UTC, Morzan6 commented
if they deleted Russian providers, then why didn’t they remove Israeli providers as well?
let's be fair

2024-08-29 04:38 UTC, MaxOinRU approved these changes

2024-08-29 04:57 UTC, batonogov approved these changes

2024-08-29 05:01 UTC, kotvkvante commented
> > @peter-volkov
> > ...And here goes another day Russians once again compare themselves to Holocaust victims :))
> 
> You DO realize that 20m of Russian civilian population were murdered in that WW2 thing, do you? Overwhelmingly by several European countries that pretend to be pinnacles of democratic virtues today. While backing same Banderites as 80 years ago and attacking Russia once again, no less.
> 
> Please disappear and take your narratives with you.

Not Russians, USSR civilians. There are were Russians, Ukrainians, Belarusians, and a lot others.

2024-08-29 05:03 UTC, kotvkvante commented
> if they deleted Russian providers, then why didn’t they remove Israeli providers as well? let's be fair

Lets be fair and remove everything made by Russians from open source.

2024-08-29 06:01 UTC, Morzan6 commented
> > if they deleted Russian providers, then why didn’t they remove Israeli providers as well? let's be fair
> 
> Lets be fair and remove everything made by Russians from open source. 

but, this will break the internet
so I don't recommend to do it😁

2024-08-29 06:18 UTC, bayram-dev approved these changes

2024-08-29 06:45 UTC, specialtactics commented
In addition to this, I would like to know what is going to be done to prevent future abuse as was showcased in https://github.com/opentofu/registry/pull/817

It is not acceptable that a widely used, open-source, community project can be mishandled so poorly.

2024-08-29 07:01 UTC, RuslanShf commented
I think you can't put your personal interests above the principles of open source community. This is a sign of disrespect for the entire free world. No matter which kind of reasons and restrictions you mean. All of them just in your head.

2024-08-29 07:59 UTC, Crandel commented
> This is a sign of disrespect for the entire free world.

You are not belong to the free world

2024-08-29 08:02 UTC, gecube commented
@Crandel I'd like to ask not to post such a comments because they only create more hate. Also I apologise before my Israeli friends because of almost racist comments on the thread regarding Israel politics against Palestine. All this fight between people is not productive and even more - there are dark forces in the world and large enterprises which are happy to do such a chaos.

2024-08-29 08:05 UTC, vtopc requested changes
Stop paying taxes to russian government and then we can discuss this.

2024-08-29 08:06 UTC, he0s commented
In my opinion, this case must be addressed to the Linux Foundation, since it has pretty clear explanation on how open-source projects should follow the laws about sanctions and so on [1]:
```
Under the EAR, the term “export” has a broad meaning. Exports can include not only the transfer of a physical product from inside the US to an external location but also other actions. The simple act of releasing technology to someone other than a US citizen or lawful permanent resident within the United States is deemed to be an export, as is making available software for electronic transmission that can be received by individuals outside the US.

This may seem alarming for open source communities, but the good news is open source technologies that are published and made publicly available to the world are not subject to the EAR. Therefore, open source remains one of the most accessible models for global collaboration.

For the purposes of compliance with the EAR, if the open source technology is publicly available without restrictions upon its further dissemination, then it is “published” and therefore “not subject to” the EAR.
```

In addition to that, it seems like, the act of removing all the providers violates the OpenTofu manifest, which is published on the community site: [2].

I can't find any information about registration as a US- or EU-based company, thus it's questionable if the community decides to follow and apply trade sanctions.

Links:
1. https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects
2. https://opentofu.org/manifesto/

2024-08-29 08:09 UTC, gecube commented
@he0s Hi! I think that they mentioned that they are using some US located hosting for storing and hosting provider modules...

2024-08-29 08:13 UTC, he0s commented
@gecube it should be explained then. If they decided to follow the "rule based order" approach, it should be evaluated their umbrella companies, which logotypes and references they have on the site.

2024-08-29 08:13 UTC, nepridumalnik commented
> > This is a sign of disrespect for the entire free world.
> 
> You are not belong to the free world

Still, I advise you to leave the hate speech aside, that's what really destroys freedom in the world.

2024-08-29 08:21 UTC, Crandel commented
> I advise you to leave the hate speech aside

Show me the hate speech? This is not a hate speech, this is just a fact.

2024-08-29 08:24 UTC, nepridumalnik commented
> > I advise you to leave the hate speech aside
> 
> Show me the hate speech? This is not a hate speech, this is just a fact.

I was talking about the quote from "You are not belong to the free world". This is a very arrogant phrase, which is intended to be an obvious insult.

2024-08-29 08:28 UTC, Crandel commented
> This is a very arrogant phrase, which is intended to be an obvious insult.

This is obviously a manipulation and total lie.

2024-08-29 08:33 UTC, efadeev approved these changes

2024-08-29 08:34 UTC, nepridumalnik commented
> > This is a very arrogant phrase, which is intended to be an obvious insult.
> 
> This is obviously a manipulation and total lie and destroy freedom in the world

I'm glad you've started to understand that.

2024-08-29 08:43 UTC, RuslanShf commented
> You are not belong to the free world
You don't know about me nothing. 

Freedom exists first and foremost in every person. I personally believe in this. Freedom of a person and humanity is not equal to any constructions of a state or nationality. If your freedom depends on location or surrounding events - that's your problem. Don't be brainwashed

2024-08-29 08:44 UTC, he0s commented
In addition to my [comment](https://github.com/opentofu/registry/pull/824#issuecomment-2316969944), a text taken from the LF site, which shows its motto:
```
The Linux Foundation is a 501(c)(6) non-profit that provides a neutral, trusted hub for developers and organizations to code, manage, and scale open technology projects and ecosystems.
```

It's clear to me, if a project is included into this organization, its decision should be aligned with the Linux Foundation mission and rules.

We definitely need to find a lawyer, who could explain us all the detail according to the LF rules, as well as alignment with the Apache Foundation licensing.

2024-08-29 08:51 UTC, Crandel commented
> n addition to that, it seems like, the act of removing all the providers violates the OpenTofu manifest, which is published on the community site: [2].

This is a lie as always. These providers are used to produce russian propaganda and cover russian hackers, help them to attack all world. It is not a place for them. Make you own registry.

2024-08-29 08:53 UTC, Crandel commented
> Freedom exists first and foremost in every person.

Yep, so why you are protecting russian state companies? If you are free, use free providers, not providers, who attack all civilized world.

2024-08-29 08:53 UTC, gecube commented
@crandel please stop.

> These providers are used to produce russian propaganda and cover russian hackers

then we need to abandon all open-source because Ukranian and Chinese hackers also use Linux and OS technologies, right? And also we need to forbid all vendors of hammers, kitchen knives etc.

2024-08-29 08:55 UTC, Crandel commented
> And also we need to forbid all vendors of hammers, kitchen knives etc.

As always lie and manipulation. I don't expect anything else from sber and yandex protectors

2024-08-29 08:57 UTC, he0s commented
> These providers are used to produce russian propaganda and cover russian hackers, help them to attack all world.

The whole Internet should be switched off, since it produces porno, harmful and violent content. Every byte of it is poison and should be banned as well as words, because they can be used to exchange information about drugs, planning terroristic acts and so on.

2024-08-29 08:58 UTC, vtopc commented
> yandex protectors

https://github.com/JustMarfix is yandex employee! Not just a protector.

2024-08-29 09:03 UTC, RuslanShf commented
> > Freedom exists first and foremost in every person.
> 
> Yep, so why you are protecting russian state companies? If you are free, use free providers, not providers, who attack all civilized world.
I defend the principles of an open source community, in which there is no place for such concepts as nations, nationalities and states. Any attempt to divide the community is counterproductive and makes our world less free.

2024-08-29 09:05 UTC, hrueschwein commented
Reading comments in this topic i realised that GitHub is really missing the clown reaction.

2024-08-29 09:05 UTC, RFOTQ approved these changes

2024-08-29 09:07 UTC, litelitelite approved these changes

2024-08-29 09:08 UTC, Crandel commented
> The whole Internet should be switched off, since it produces porno, harmful and violent content. Every byte of it is poison and should be banned as well as words, because they can be used to exchange information about drugs, planning terroristic acts and so on.

You can't stop manipulating and playing victim, don't you?

2024-08-29 09:09 UTC, Crandel requested changes
Violates current policy

2024-08-29 09:09 UTC, ansromanov commented
The irony is that such actions do not harm Russian cloud providers, as they have their owned registry mirrors. For example, from the Yandex Cloud documentation:

```
provider_installation {
  network_mirror {
    url = "https://terraform-mirror.yandexcloud.net/"
    include = ["registry.terraform.io/*/*"]
  }
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
}
```
However, these actions undoubtedly harm the reputation of OpenTofu as a young open-source project, which, according to the OpenTofu Manifesto, was created to ensure the freedom of Terraform’s source code and the associated infrastructure. I think it also casts a shadow on the companies behind OpenTofu’s development, such as Gruntwork, Spacelift, env0, and others.

I can assume that some OpenTofu users might switch back to Terraform. In this case, HashiCorp’s stance appears more straightforward, as they have explicitly stated their control over the development and distribution of their product under the BSL, a conditionally open license.

Overall, this is another concerning sign for the global open-source community.

2024-08-29 09:13 UTC, Crandel commented
> However, these actions undoubtedly harm the reputation of OpenTofu as a young open-source project, which, according to the OpenTofu Manifesto, was created to ensure the freedom of Terraform’s source code and the associated infrastructure.

As always this is a manipulation. I don't see in this registry any providers from Iran or North Korea or from pornhub for example. Freedom is not equal to do-everything-I-like.

2024-08-29 09:18 UTC, he0s commented
> You can't stop manipulating and playing victim, don't you?

Well, you are a troll. I see that, since you took a side.

This not that kind of discussion. I'm for open source being open source with all the rules and laws around it. If you put a project under a world-wide foundation's umbrella, it's your responsibility to make sure it follows its rules and all the decision made are for making the community inclusive, diverse and so on. If it's not, it's a subject for legal investigation and excluding from the foundations if they violated the laws. One more time: **based on legal, not someone's opinion taken out from nowhere**.

2024-08-29 09:19 UTC, he0s approved these changes

2024-08-29 09:27 UTC, nepridumalnik commented
Let's keep open source open source, not slightly open source or semi-open source. Leave a personal opinion about this outside the platform and let's learn to live together.

2024-08-29 09:31 UTC, gecube approved these changes

2024-08-29 09:40 UTC, Crandel commented
> Well, you are a troll. I see that, since you took a side.

And you are the terrorist. I can see this, since you are protecting terrorist organizations.

2024-08-29 09:44 UTC, Daxenirean commented
That's what happens when brainwashed people are given at least some kind of power. A living example is this @Crandel

2024-08-29 09:45 UTC, pyToshka approved these changes

2024-08-29 09:48 UTC, Crandel commented
> That's what happens when brainwashed people are given at least some kind of power

And this is exactly a hate speech.

2024-08-29 09:50 UTC, gecube commented
@pyToshka thanks

2024-08-29 09:52 UTC, unStatiK commented
A beautiful world where racism is condemned but Russophobia is fully supported.

2024-08-29 09:53 UTC, timurgen approved these changes
LGTM

2024-08-29 09:54 UTC, kvendingoldo approved these changes

2024-08-29 09:56 UTC, vnmsklnk commented
> > Well, you are a troll. I see that, since you took a side.
> 
> And you are the terrorist. I can see this, since you are protecting terrorist organizations.

I believe you can always defend against terrorism much more effectively from your own country, but not from Germany.

2024-08-29 09:57 UTC, Slach approved these changes

2024-08-29 09:58 UTC, he0s commented
@Slach, thank you!

2024-08-29 10:19 UTC, Dok-dev approved these changes

2024-08-29 10:24 UTC, Crond-Fx commented
> > > @peter-volkov
> > > ...And here goes another day Russians once again compare themselves to Holocaust victims :))
> > 
> > 
> > You DO realize that 20m of Russian civilian population were murdered in that WW2 thing, do you? Overwhelmingly by several European countries that pretend to be pinnacles of democratic virtues today. While backing same Banderites as 80 years ago and attacking Russia once again, no less.
> > Please disappear and take your narratives with you.
> 
> Not Russians, USSR civilians. There are were Russians, Ukrainians, Belarusians, and a lot others.

Russian Federation is a rebranded USSR, as USSR was a rebranded Russian Empire. It's the same people with same nationalities on same lands. Therefore, it is a shared loss.

2024-08-29 10:26 UTC, SerhiiK commented
> > Russian programmers are not to blame for spyware? Bots? Attacks on critical infrastructure all around the world we hear on a daily basis?
> 
> Wow. Just wow. Do you know who else once were blaming a big group of people by nationality, citng some specific and hardly credible crimes?

I know who else - Ukrainian by Russians and you keep doing it now.

2024-08-29 10:26 UTC, Dok-dev approved these changes

2024-08-29 10:27 UTC, Crond-Fx approved these changes

2024-08-29 10:27 UTC, b4d-user approved these changes

2024-08-29 10:28 UTC, SadmL approved these changes

2024-08-29 10:29 UTC, kvendingoldo commented
Let's talk about the future of OpenTofu in scope of CNCF here: https://github.com/cncf/sandbox/issues/81

2024-08-29 10:39 UTC, Crandel commented
> Russian Federation is a rebranded USSR, as USSR was a rebranded Russian Empire. It's the same people with same nationalities on same lands.

This is a lie as always. Stop sharing russian propaganda.

2024-08-29 10:50 UTC, degibenz commented
> if they deleted Russian providers, then why didn’t they remove Israeli providers as well? let's be fair

`you don't understand, this is different` ([mem](https://cyclowiki.org/wiki/Вы_не_понимаете,_это_другое))

2024-08-29 10:51 UTC, Egor3f approved these changes

2024-08-29 10:57 UTC, quantum-swiss approved these changes

2024-08-29 10:58 UTC, GrakovNe commented
Hope that opensource COULD avoid the politic because this is Pandora's box

Glad to see how OpenTofu comminity take adequate response in attempt to ruin it's reputation

2024-08-29 11:01 UTC, Frolls approved these changes

2024-08-29 11:06 UTC, dyadMisha approved these changes

2024-08-29 11:07 UTC, Crandel commented
> Glad to see how OpenTofu comminity take adequate response in attempt to ruin it's reputation

It's not a community, these are russian bots, playing victims and crying on freedom, while other russian are killing innocent people in Ukraine

2024-08-29 11:10 UTC, a-osipov-pixonic approved these changes

2024-08-29 11:10 UTC, nikicat commented
> > Glad to see how OpenTofu comminity take adequate response in attempt to ruin it's reputation
> 
> It's not a community, these are russian bots, playing victims and crying on freedom, while other russian are killing innocent people in Ukraine

You're quite correct, that there are russians that are victims, and there are _other_ russians that are killing innocent people in Ukraine.

2024-08-29 11:13 UTC, AlekseiKulberg approved these changes

2024-08-29 11:13 UTC, fuck-you-moron commented
> killing innocent people in Ukraine
Ukraine started killing innocent people in Ukraine in 2014

2024-08-29 11:15 UTC, leernd007 commented
Go vote again for Putin, country of slaves, vodka and shit. You deserve access only to your TV, but not to the technological world.

2024-08-29 11:16 UTC, timurgen commented
> Go vote again for putin (hyilo), country of slaves, vodka and shit. You deserve access only to your TV, but not to the technological world.

hate speech

2024-08-29 11:16 UTC, sberdashkevich approved these changes

2024-08-29 11:17 UTC, sberdashkevich commented
LGTM

2024-08-29 11:18 UTC, SerhiiK commented
> > killing innocent people in Ukraine
> 
> Ukraine started killing innocent people in Ukraine in 2014

Here we go, Russian propaganda bot. Where have you been these 8 years?

2024-08-29 11:24 UTC, Reckoner911 commented
> > Это признак неуважения ко всему свободному миру.
> 
> Ты не принадлежишь к свободному миру.

Это говорит тот самый человек, который уехал из своей страны потому что бежал от призыва.
Именно этот человек говорит о свободе.
----
Никто в сообществе опенсорса не будет пресмыкаться перед украинцем, или русским или любым другим человеком, в зависимости от его нации или его происхождения.
Поэтому убери свои грабли от клавиатуры, бот.

2024-08-29 11:25 UTC, SerhiiK commented
> > > Это признак неуважения ко всему свободному миру.
> > 
> > 
> > Ты не принадлежишь к свободному миру.
> 
> Это говорит тот самый человек, который уехал из своей страны потому что бежал от призыва. Именно этот человек говорит о свободе.
> 
> Никто в сообществе опенсорса не будет пресмыкаться перед украинцем, или русским или любым другим человеком, в зависимости от его нации или его происхождения. Поэтому убери свои грабли от клавиатуры, бот.

hate speech

2024-08-29 11:25 UTC, fuck-you-moron commented
> Go vote again for putin

Yes, we still have an elections in Russia. Go vote for someone in Ukraine :)

2024-08-29 11:29 UTC, kvendingoldo commented
@opentofu when maintainers team will break the silence and post an official press-release? it's interesting to get a question to the following topic:
1. what's about returning provider to registry
2. what's about unblocking registry
3. what's about exclusion of OpenTofu from CNCF
4. what's about exclusion of politically affected opentofu maintainers?

2024-08-29 11:32 UTC, kunaksergey commented
Let's stop the return of Mordor!!!

2024-08-29 11:32 UTC, kvendingoldo commented
> Let's stop the return of Mordor!!!
Hate speech

2024-08-29 11:32 UTC, RuslanShf commented
> > > Glad to see how OpenTofu comminity take adequate response in attempt to ruin it's reputation
> > 
> > 
> > It's not a community, these are russian bots, playing victims and crying on freedom, while other russian are killing innocent people in Ukraine
> 
> You're quite correct, that there are russians that are victims, and there are _other_ russians that are killing innocent people in Ukraine.

Please stop with political discussions. Both sides. 

A person who is consumed by hatred for any social group—whether based on nationality or country—is not truly free. Even if they live in a "free country," their mindset keeps them from experiencing true freedom. To grasp the principles of freedom and libertarianism that inspired the founders of open communities, one must first be a free individual.

2024-08-29 11:35 UTC, fuck-you-moron commented
@opentofu please also remove all comments with khokhlo hate speach

2024-08-29 11:35 UTC, ZaneHero approved these changes

2024-08-29 11:36 UTC, Reckoner911 commented
@cam72cam 
@opentofu
lmao man, u are so disgusting
I ask u to delete all of russian code in this project if u gonna to delete russian providers.....

2024-08-29 11:38 UTC, Reckoner911 commented
maaaan, i can repeat
@cam72cam
lmao man, u are so disgusting
I ask u to delete all of russian code in this project if u gonna to delete russian providers.....

2024-08-29 11:38 UTC, Reckoner911 commented
maaaan, i can repeat
@cam72cam
lmao man, u are so disgusting
I ask u to delete all of russian code in this project if u gonna to delete russian providers.....
lol

2024-08-29 11:42 UTC, GEK62 approved these changes

2024-08-29 11:45 UTC, Egor3f commented
Please stop swearing (everyone). OSS is the worst place for political brawls

![i (1)](https://github.com/user-attachments/assets/3ae6bd3c-dd24-4475-88d1-b2f8ad3b95cc)

2024-08-29 11:46 UTC, GrakovNe commented
> > > Glad to see how OpenTofu comminity take adequate response in attempt to ruin it's reputation
> > 
> > 
> > It's not a community, these are russian bots, playing victims and crying on freedom, while other russian are killing innocent people in Ukraine
> 
> You're quite correct, that there are russians that are victims, and there are _other_ russians that are killing innocent people in Ukraine.

this is out of discussing topic, sorry. I'd like to not merge my personal political preferences within peoples who never asked it.

My own opensource projects are available to every single people from any country, state, city and nation. And i bet that's the only way which could be in the opensource if we still wanna to keep opensource itself

2024-08-29 12:12 UTC, WhiteApfel requested changes
PR is created for use with Russian sanctioned businesses only.

2024-08-29 12:14 UTC, he0s commented
@WhiteApfel please follow the Linux Foundation explanation of the sanctions implementation: https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects.

2024-08-29 12:25 UTC, WhiteApfel commented
@he0s, and this is not a question of sanctions, it's a question of Maintainers' ethical attitudes. And from an ethical point of view, there is a dubious point here, because no correct use of this code is assumed, except for the operation of Russian business.

2024-08-29 12:25 UTC, gecube commented
@WhiteApfel totally wrong assumption.

2024-08-29 12:29 UTC, dzaytsev91 commented
> @he0s, and this is not a question of sanctions, it's a question of Maintainers' ethical attitudes. And from an ethical point of view, there is a dubious point here, because no correct use of this code is assumed, except for the operation of Russian business.

It's not a personal project of Maintainers, it's a part of Linux Foundation thus should follow the Linux Foundation rules and principals.

2024-08-29 12:41 UTC, WhiteApfel commented
@dzaytsev91, does the Linux Foundation prohibit changes unless 50%+1 of the community votes in favor of the change? (And how is the community defined? A list of people who gave the project a star?) The final decision rests with the project team.

2024-08-29 12:44 UTC, kvendingoldo commented
@WhiteApfel yes, that's the rule. I think, that OpenTofu can create a fork, which is not following any standards and do there anything that they want, but not in the scope of rules of the current project

2024-08-29 12:44 UTC, Areso commented
> The final decision rests with the project team.
Logical enough, but so far in favour voted only 3 people out of 22.

2024-08-29 12:47 UTC, gecube commented
what is interesting - the complete silence from the maintainers... like they don't know how to react and what to do.

2024-08-29 12:47 UTC, LogansUA commented
These comments are so funny to read, all "good" russians started to whiny about restricting them in some way, talking about opensource'ness, freedom, the "same Banderites" (that's funny as hell), but continue supporting everything that their county is doing, typical hypocrites.

Another example of "good" russians standing for democratic values in the comment section rather than in their own country.

2024-08-29 12:53 UTC, kitsunoff commented
Russian cloud providers are used not only in Russia, but also in the CIS countries. Also, these cloud providers do not violate US export rules. I decided to check what ChatGPT thinks and that's what it thinks.



"U.S. export control laws, such as the Export Administration Regulations (EAR) and the regulations enforced by the Office of Foreign Assets Control (OFAC), include restrictions on the export of certain goods, technologies, and services to specific countries, including Russia.

However, open-source software generally has a special status. In most cases, software that is released as open source and made publicly available without export restrictions is not subject to U.S. export control laws. This is because open-source code, which is freely accessible to the public (e.g., on platforms like GitHub), is typically not considered controlled technology.

That said, there are important exceptions and nuances:

Encryption Export Controls: If open-source software includes advanced encryption features, it might still be subject to export controls, even if it is publicly available. In such cases, an export license might be required.

Sanctions Lists: If you are dealing with entities or individuals who are on U.S. sanctions lists (such as those maintained by OFAC), even open-source software may be prohibited from being provided to those parties.

Specialized Software: Certain types of software, even if open source, might require export licenses if they fall under specific control lists, such as those related to nuclear, military, or other strategically important technologies.

In summary, open-source software is generally not subject to U.S. export restrictions unless it contains controlled encryption technology or is being provided to sanctioned entities. However, it's crucial to consider the specific details of each situation and, if necessary, consult with a lawyer who specializes in export control compliance."

(c) ChatGPT

Then why do I need OpenTofu if it is not Open and even HashiCorp does not allow itself to do this (I can download yandex cloud provider via vpn right now from their registry because the Russian IP is in the block)

And as they said above, if this is a desire to harm, then it does not work. It only ruins the reputation for an open source project.

2024-08-29 12:58 UTC, kotvkvante commented
> These comments are so funny to read, all "good" russians started to whiny about restricting them in some way, talking about opensource'ness, freedom, the "same Banderites" (that's funny as hell), but continue supporting everything that their county is doing, typical hypocrites.
> 
> Another example of "good" russians standing for democratic values in the comment section rather than in their own country.

What do you know about what this 《"good" russians》doing or not for 《democratic》?  Do you expect us to send you a photo of us with posters in front of the Kremlin saying: " российское правительство будь хорошим не обижай никого"?

2024-08-29 13:00 UTC, dahnlka approved these changes

2024-08-29 13:02 UTC, stickyb1t approved these changes

2024-08-29 13:02 UTC, sircthulhu approved these changes

2024-08-29 13:02 UTC, zartdinov commented
Guys, forget it. Close PR. Leave the people with their project.

2024-08-29 13:03 UTC, dpshnv approved these changes

2024-08-29 13:06 UTC, ZverGuy commented
> Guys, forget it. Close PR. Leave the people with their project.

Nope
This is project under Linux Foundation, and then follow the principies of the Linux Foundation

2024-08-29 13:07 UTC, cam72cam commented
Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.

We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.

2024-08-29 13:07 UTC, Sigura commented
Exactly open source has ended on USA hosted services for despised by nationality or location. Lol. Close it all.

https://ofac.treasury.gov/media/932951/download?inline

2024-08-29 13:13 UTC, he0s commented
I assume it worth involving into discussion @mkdolan as a representative of the Linux Foundation. If I'm wrong with mentioning, please refer us to a person who could help us to clarify all the nuances.

2024-08-29 13:19 UTC, etki commented
Just a kind reminder that demanding anything from open source is way more offensive rather than maintainers doing any decisions. While we can ask, suggest and say that we're not aligned with decisions, the ones that are in the charge are, well, in charge and can act on their own, change their directions, decide what their responsibilities are, by what rules their own piece of world works, so much mentioned living beings with their own free will. Consumers and side contributors have the right and an option to act in dropping support one way or another, disagree, but they can't decide for other people.

Some of the backlash in the current state of things in the world comes exactly from there. Polite "i see that you've done X; i want to provide an opinion" is a very different thing and something you may actually consider; endless "we're so offended" cries and demands don't.

2024-08-29 13:39 UTC, zartdinov commented
> Some of the backlash in the current state of things in the world comes exactly from there. Polite "i see that you've done X; i want to provide an opinion; i know that you're have the right to do it, but i think it's not the best action to take" is a very different thing and something you may actually consider; endless "we're so offended/oppressed" cries and demands aren't.

I don't think many people are offended or crying. No need to make things up.

2024-08-29 13:46 UTC, kvendingoldo commented
Folks, let's start to think about the fork of OpenTofu until the August 26. Vote for this

2024-08-29 13:47 UTC, Draiget approved these changes

2024-08-29 13:52 UTC, ZverGuy commented
> Folks, let's start to think about the fork of OpenTofu until the August 26. Vote for this

RuTofu :)

2024-08-29 13:56 UTC, lexfrei approved these changes

2024-08-29 13:57 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
> RuTofu :)
> 
> 
> Or maybe CozyTofu

[Omichka](https://ru.wikipedia.org/wiki/%D0%9E%D0%BC%D0%B8%D1%87%D0%BA%D0%B0_(%D1%81%D1%8B%D1%80)) would have been much better.

2024-08-29 13:58 UTC, tropicoo commented
@zartdinov 
> I don't think many people are offended or crying. No need to make things up.

I believe you have missed [this pull request](https://github.com/opentofu/registry/pull/825) where Russians made unacceptable comments with hate speech (typical for Russian imperialists) regarding Ukrainians and the situation overall. As a result, those comments were removed.

2024-08-29 14:01 UTC, ZverGuy commented
> Russian imperialists

Hate Speech

2024-08-29 14:02 UTC, nepridumalnik approved these changes

2024-08-29 14:03 UTC, lunatik13 commented
> @zartdinov
> 
> > I don't think many people are offended or crying. No need to make things up.
> 
> I believe you have missed [this pull request](https://github.com/opentofu/registry/pull/825) where Russians made unacceptable comments with hate speech (typical for Russian imperialists) regarding Ukrainians and the situation overall. As a result, those comments were removed.

bla bla bla 
The Ukrainian night is quiet. But the lard needs to be hidden.

2024-08-29 14:03 UTC, ZverGuy approved these changes
Awesome PR

2024-08-29 14:03 UTC, sabretus commented
> > Folks, let's start to think about the fork of OpenTofu until the August 26. Vote for this
> 
> RuTofu :)
> 
> Or maybe CozyTofu

Exactly, this can be done even in separate Russian Internet, called Cheburnet, running on Russian own home-grown OS - Bolgenos!

2024-08-29 14:06 UTC, DmitryShonin commented
All those *restrictions* do not make sense, since all who really need such stuff will use proxy. And just in case there's official yandex mirror for all tf providers.

2024-08-29 14:06 UTC, specialtactics approved these changes

2024-08-29 14:08 UTC, kvendingoldo commented
@DmitryShonin  yep, but I think that people who have self-esteem will avoid OpenTofu starting from this moment, and it's the beginning of the end of such cool project.

2024-08-29 14:20 UTC, sys-av approved these changes

2024-08-29 14:22 UTC, metalim commented
> yep, but I think that people who have self-esteem will avoid OpenTofu starting from this moment, and it's the beginning of the end of such cool project.

It might be much worse. If this deletion will stay intact in OpenTofu, other maintainers will support similar decision with "stare decisis" principle. It'll be snowball effect ruining whole Open Source community once and forever.

No pressure

2024-08-29 14:22 UTC, Zulcom commented
The PR: "the removal of Russian-linked providers has nothing to do with compliance with sanctions, which I explained above"
The OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee statement, 200 comments and 2 days afrer (initial pr was merged in 58 mins):
> We have taken proactive steps to ensure compliance with relevant sanctions
> we are working on a more detailed response

I would like to suggest that the Technical Steering Committee consider taking proactive measures to ensure compliance **with their community** standards within a period of two days and two hundred comments. After that, they could take agreed-upon steps within fifty-eight minutes.
Other open-source software communities employ a similar strategy and thrive without political controversy. This approach could also be effective for the proactivesanctionscompliencetofu community too.

2024-08-29 14:35 UTC, clovexx approved these changes

2024-08-29 14:37 UTC, aofodo approved these changes

2024-08-29 14:43 UTC, oifj34f34f commented
Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple.
Again, stop working for the regime and playing the victim.

2024-08-29 14:47 UTC, VladimirTyrin approved these changes

2024-08-29 14:48 UTC, vladon commented
> Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple. Again, stop working for the regime and playing the victim.

Why aren't you fighting at the front?

2024-08-29 14:52 UTC, oifj34f34f commented
> > Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple. Again, stop working for the regime and playing the victim.
> 
> Why aren't you fighting at the front?

Why? I want to live. Although anything is possible, mogilization in Russia could happen again.
Я из РФ, если ты не понял.

2024-08-29 14:54 UTC, MikhailAseev approved these changes

2024-08-29 14:59 UTC, ksn135 commented
> Я из РФ, если ты не понял.

Бро, не стоит желать вреда своей стране. Мне жаль тебя. Претензии к стране - это претензии, прежде всего, к самому себе. Что-то не получилось, не сбылось, не срослось в свое время. Вот и хочется палками и камнями от обиды кидаться.

2024-08-29 15:00 UTC, b4d-user commented
> > > Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple. Again, stop working for the regime and playing the victim.
> > 
> > 
> > Why aren't you fighting at the front?
> 
> Why? I want to live. Although anything is possible, mogilization in Russia could happen again. Я из РФ, если ты не понял.

Хорошо, почему тогда не на баррикадах? Почему не в главе оппозиционного движения? Почему ТЫ не альтернатива для жителей России?

2024-08-29 15:00 UTC, ZverGuy commented
> Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple.
> Again, stop working for the regime and playing the victim.

Hmm
Ok
Come with me
:)

2024-08-29 15:01 UTC, lunatik13 commented
> Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple. Again, stop working for the regime and playing the victim.

It is not posible, for stop **it** need change your mind

2024-08-29 15:07 UTC, faust93 commented
> Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple. Again, stop working for the regime and playing the victim.

Bro! I would really appreciate, as well as many of those unlucky ppl who are stuck in totalitarian regimes as for today, for the know-how! Could you provide simple step-by-step instruction on this topic? Smth like "How stop tolerating and change your government for Dummies"?

2024-08-29 15:08 UTC, cam72cam commented
Reminder to keep this civil. If that can't be accomplished, this thread will be locked.

2024-08-29 15:10 UTC, tsunamaru commented
Продам гараж

2024-08-29 15:10 UTC, b4d-user commented
> Продам гараж

Где и за сколько?

2024-08-29 15:12 UTC, dmorozov82 commented
Will anyone port codebase to LGBTQ++ from Golang?

2024-08-29 15:20 UTC, lunatik13 commented
Okay guys. It's fun with you, but I have to feed the bear and then install a toilet from Ukraine.

2024-08-29 15:24 UTC, oifj34f34f commented
> Бро, не стоит желать вреда своей стране. Мне жаль тебя. Претензии к стране - это претензии, прежде всего, к самому себе. Что-то не получилось, не сбылось, не срослось в свое время. Вот и хочется палками и камнями от обиды кидаться.

Где я желал вреда своей стране?
Перестаньте быть наивными и путать власть и страну. Не думаю, что большинство россиян, к примеру, поддержали блокировку YouTube.

> Хорошо, почему тогда не на баррикадах? Почему не в главе оппозиционного движения? Почему ТЫ не альтернатива для жителей России?

Пока что хватит того, что я не пишу ксенофобские комментарии в защиту режима.

2024-08-29 15:25 UTC, Kozoft approved these changes

2024-08-29 15:26 UTC, he0s commented
I think everyone should say "thank you" to the moderator who been involved into this discussion. He or she may provide us a way to make donates on beer or wine. :)

2024-08-29 15:26 UTC, 0xF6 commented
Again stupid politics in github and in general in open source
it is very sad that engineers behave like children

2024-08-29 15:26 UTC, ivan-vorona commented
came here to see some russians crying and telling everyone they and their goverment-ran companies which were removed in the previous PR are not to blame
I am satisfied

2024-08-29 15:27 UTC, dmytrobraha requested changes
According to new policy, this PR should be closed and rejected

2024-08-29 15:29 UTC, b4d-user commented
> Пока что хватит того, что я не пишу ксенофобские комментарии в защиту режима

Большинство ксенофобских комментариев тут затерты (что правильно).
Вот только я правильно понимаю, что пока остальные будут свергать власть по твоему совету, ты будешь сидеть в сторонке со словами "Ну я ксенофобские комментарии не писал и этого достаточно, пусть остальные поработают"

2024-08-29 15:31 UTC, godev02 commented
There is no trust in those who make such decisions, because at any moment you can release an update that will create malicious activity (as node-ipc already did) for users from countries you don't like for political reasons. I believe that clowns should be chased off the first time, and absolutely boycott any use of your software after this incident.

2024-08-29 15:38 UTC, DmitryShonin commented
> Russians, stop complaining. If you want to not be sanctioned, stop tolerating and change your government. It's simple.
> Again, stop working for the regime and playing the victim.

We work for money to make our families as happy as we can do, not for *the regime* 
So called *sanctions* does not work at all. You might be very surprised but here in Russia we have iPhones, MacBooks, pixels and fast internet.
Just stop being an idiot...

2024-08-29 15:44 UTC, omar-nahhas commented
I am lucky to be in the part of the word that thinks can control the other other part to slavery. I get to keep  my providers

2024-08-29 15:46 UTC, AndreyPilipenko commented
> I think that open source is not a place for politics. For what purpose would you remove something related to Russia? For what? Please, don't do bad things to Russian programmers, we are not to blame for what is happening. We help open source just like you help us all.

purpose is such county doesn't exist

2024-08-29 15:50 UTC, Freezerno commented
> Россияне, перестаньте жаловаться. Если вы не хотите попасть под санкции, перестаньте терпеть и смените правительство. Все просто. Еще раз, перестаньте работать на режим и разыгрывать жертву.

If you're homeless, just buy a house.

2024-08-29 15:53 UTC, pryschepa commented
Open source community is no-politics place, but, will you be glad to work with some terrorists like North Korea hackers? 

just to remind, Russia has more U.S. sanctions than NK and Iran combined. All these 'sberbank' and 'yandex' are under world-wide sanctions.

That is what is called 'evil', so, if we talk about terrorists using open-source software to continue making bad things... i think its not ok.

2024-08-29 15:57 UTC, omar-nahhas commented
I am lucky to be the part of the world that does not  (really not ) go around subjugating the rest of the world, stealing their resources, destroying them with illegals wars and then if they dare to resist, tagging them as "the enemy".

2024-08-29 16:01 UTC, grem11n requested changes
OpenTofu as a community should respect the international law, which caused the original PR.

This revert is a regression in all meanings of the word.

2024-08-29 16:01 UTC, rusik69 commented
> I am lucky to be the part of the world that does not (really not ) go around subjugating the rest of the world, stealing their resources, destroying them with illegals wars and then if they dare to resist, tagging them as "the enemy".

me too!

2024-08-29 16:02 UTC, omar-nahhas commented
"international law" is a f***g joke. Strange you did not realised ruing the past 6 months.

2024-08-29 16:04 UTC, SerhiiK commented
> > Folks, let's start to think about the fork of OpenTofu until the August 26. Vote for this
> 
> RuTofu :)
> 
> Or maybe CozyTofu

just use the heritage of Russian culture and call it **Snochakh**

2024-08-29 16:05 UTC, VirtualZer0 commented
@pryschepa then don't forget to delete all code sections written by people from Russia, Iran and other “terrorists”. Be consistent in your position, otherwise it turns out that you are using a product that “terrorists” were involved in creating. I am afraid to imagine how you sleep at night realizing that part of your libs and apps was written by “evil Russians”.

2024-08-29 16:07 UTC, VirtualZer0 approved these changes

2024-08-29 16:14 UTC, kvendingoldo commented
@VirtualZer0 and maintainers team should not forget to stop using Nginx / K8S and other tools as well due to evil code inside of these tools.

2024-08-29 16:22 UTC, rusik69 commented
> if we talk about terrorists using open-source software to continue making bad things... i think its not ok.

thats just a side effect of free information, it can be used by everyone

2024-08-29 16:28 UTC, mxshooter approved these changes

2024-08-29 16:39 UTC, sdwvit requested changes
;)

2024-08-29 16:40 UTC, far-rainbow commented
> just use the heritage of Russian culture and call it **Snokhaсh**

So your country's heritage version would be **Schluhach**?

2024-08-29 16:47 UTC, Insidexa commented
русня прийміть свою нікчемну реальність, далі буде тільки гірше

2024-08-29 16:52 UTC, Insidexa commented
Github, being an American company, must comply with sanctions
That's all you need to know :) It's a great time

2024-08-29 16:56 UTC, Insidexa commented
> > Бро, не стоит желать вреда своей стране. Мне жаль тебя. Претензии к стране - это претензии, прежде всего, к самому себе. Что-то не получилось, не сбылось, не срослось в свое время. Вот и хочется палками и камнями от обиды кидаться.
> 
> Где я желал вреда своей стране? Перестаньте быть наивными и путать власть и страну. Не думаю, что большинство россиян, к примеру, поддержали блокировку YouTube.
> 
> > Хорошо, почему тогда не на баррикадах? Почему не в главе оппозиционного движения? Почему ТЫ не альтернатива для жителей России?
> 
> Пока что хватит того, что я не пишу ксенофобские комментарии в защиту режима.

ти нічого не зробив щоб завершити війну.

2024-08-29 16:57 UTC, SerhiiK commented
> > just use the heritage of Russian culture and call it **Snokhaсh**
> 
> So your country's heritage version would be **Schluhach**?

You can try to offend me but Snokhachestvo is part of russian culture. Turgenev, Nekrasov, Gorky wrote about it. 
Are you ashamed of your own culture?

2024-08-29 17:03 UTC, ZverGuy commented
> Github, being an American company, must comply with sanctions
> 
> That's all you need to know :) It's a great time

when github asks to delete, then it's worth deleting. What is happening now is simply not following the principles of the Linux Foundation

2024-08-29 17:11 UTC, eshutov commented
@pryschepa

>Open source community is no-politics place

You are doing this community a political space. And I have to admit you doing that to your own detriment.
How can you be so brainwashed? (Actually that looks like a trolling.)

>terrorists like North Korea hackers

Let's be honest how many terrorists-hackers from DPRK do you know? Please, do count them.
And from the other side: what's about at least "Blackwater" private military company? Who participated in many of conflicts without being a legal participant of them and without following the rules of war? Those are thousands of men.
Dude, where are the sanctions caused by that?

Why supporters of the happening choose such (put it culturally) "strange" arguments?

2024-08-29 17:11 UTC, ZverGuy commented
> ти нічого не зробив щоб завершити війну.

Sorry, we don't understand mova. Use 
International Language please.

2024-08-29 17:12 UTC, ksn135 commented
@Insidexa 
> ти нічого не зробив щоб завершити війну.

Прав был известный киевский публицист Олесь Бузина, когда сказал "Когда украинец умнеет, он становится русским"

2024-08-29 17:12 UTC, oifj34f34f commented
> ти нічого не зробив щоб завершити війну.

Глобально, да. Но по крайней мере у меня получилось переубедить одного друга.

2024-08-29 17:15 UTC, WhiteApfel commented
> @Insidexa
> 
> > ти нічого не зробив щоб завершити війну.
> 
> Прав был известный киевский публицист Олесь Бузина, когда сказал "Когда украинец умнеет, он становится русским"

You made a very nationalistic statement.

2024-08-29 17:16 UTC, ZverGuy commented
@opentofu why you don't remove messages about war?

2024-08-29 17:18 UTC, ksn135 commented
> > Прав был известный киевский публицист Олесь Бузина, когда сказал "Когда украинец умнеет, он становится русским"
> 
> You made a very nationalistic statement.

Why? This is a direct quote from a well-known Ukrainian publicist.
Who, by the way, was murdered by nationalists and the murderers are known and have not been punished to this day.

2024-08-29 17:19 UTC, cam72cam commented
Unfortunately, this has gone too far off topic and has been locked. I apologies to all of you who were trying to discuss this issue in good faith.

2024-09-04 11:04 UTC, cam72cam commented
In discussing with the Linux Foundation, we understand this is a complex issue with many countries imposing sanctions on Russia and we do not have the community resources to figure this all out right now. Anyone in any geography could provide a similar service locally.

2026-02-09 10:57 UTC, Yantrio commented
We, The OpenTofu team, updated our policy to discuss what our stance is on accepting providers and modules here: https://github.com/opentofu/registry/blob/main/POLICY.md#provider-and-module-submission

Due to inactivity in this area and the policy upstanding for some time now I'll be closing and locking this and others related to it. Thank you

2026-02-09 10:57 UTC, closed without merging