Delete providers/m/mailrucloudsolutions directory
opentofu/registry pull request #825
Opened 2024-08-29 09:45 UTC by Crandel

Remove mailRu provider in addition to other russian based providers

2024-08-29 09:46 UTC, Crandel commented
@ollevche please review this PR

2024-08-29 09:50 UTC, TheScarletArrow commented
Delete yourself, your actions are against Linux licence policy

2024-08-29 10:13 UTC, gecube commented
You forgot to remove https://github.com/opentofu/registry/blob/main/providers/s/selectel/selectel.json

Be consistent! Remove all RUSSIAN providers please

/sarcasm/

2024-08-29 10:18 UTC, Dok-dev commented
One more ukro agent detected.

2024-08-29 10:40 UTC, Crandel commented
> One more ukro agent detected.

Hate speech

2024-08-29 11:32 UTC, Reckoner911 commented
> > One more ukro agent detected.
> 
> Hate speech

u are nazi man.... 
and u going against Linux Foundation....
such a shame....

2024-08-29 12:02 UTC, efadeev commented
Sick people have no rest...

2024-08-29 12:44 UTC, nepridumalnik commented
I found a useful search query for the author: https://github.com/search ?q=repo%3Aopentofu%2Fregistry%20rus&type=code

2024-08-29 13:07 UTC, cam72cam commented
Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.

We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.

2024-08-29 16:23 UTC, yaa110 commented
@Crandel  Don't be Difficult

2024-08-29 18:03 UTC, loysosan commented
Looks like good solution, thanks

2024-08-29 20:33 UTC, pwrsoft commented
Please remove mailRu provider and other russian based providers!

2024-08-30 08:07 UTC, dzaytsev91 commented
> Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.
> 
> We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.

Am I understood proactive steps right? Now any maintainer can block anything and anyone just because he thinks it might be (or might not) compliance issue?

2024-08-30 08:22 UTC, kvendingoldo commented
@cam72cam when official response will be ready? It's almost 24 hours gone.

2024-08-30 11:04 UTC, ait-vdykyi commented
Great changes! Thank you very much for this support and hope this is the final Russian provider)

2024-08-30 11:25 UTC, kvendingoldo commented
@ait-vdykyi you forget, that all russian code should be deleted too :) It will be a big revert to back for OpenTofu

2024-08-30 11:32 UTC, ait-vdykyi commented
> @ait-vdykyi you forget, that all russian code should be deleted too :) It will be a big revert to back for OpenTofu

So delete if you can) Create a PR please) I want to see exactly what part of the code is from Russia now, it will be very useful for all of us)

2024-08-30 11:46 UTC, Crandel commented
> you forget, that all russian code should be deleted too :) It will be a big revert to back for OpenTofu

Who you are to demand something in this repo? Create your own fork and remove whatever you want.

2024-08-30 12:11 UTC, ait-vdykyi commented
And it starts again... remove all Russian code, stories about Kazakhstan, Open Source principles, and so on. @cam72cam maybe you will also close the discussion in this PR if this continues?

2024-08-30 12:26 UTC, elaichenkov approved these changes
LGTM

2024-08-30 12:49 UTC, admito88 commented
Cool changes! Thank you very much @Crandel, I hope this PR will be accepted!

2024-08-30 12:57 UTC, kvendingoldo requested changes
Nonsense.

2024-08-30 16:56 UTC, ikaygorodov commented
> Remove mailRu provider in addition to other russian based providers

Fantastic first commit in a project.
With your help OpenTofu has made huge leap forward =)))))

2024-08-30 17:46 UTC, ait-vdykyi commented
> Fantastic first commit in a project.
> With your help OpenTofu has made huge leap forward =)))))

Oh, thank you very much for such kind words of support, I hope your first PR for OpenTofu will also be very significant, if it ever will be of course) And thank you very much, your comment here helped everyone to understand that this PR is very important, but no matter how your comment was here, no one would have understood for sure) Well done) Once again, thank you very much) I am proud of you)

2024-08-30 19:46 UTC, kvendingoldo commented
@ait-vdykyi https://en.wikipedia.org/wiki/Sarcasm

2024-08-30 20:04 UTC, vhlukhov approved these changes

2024-08-31 05:37 UTC, admito88 approved these changes

2024-08-31 05:37 UTC, ait-vdykyi approved these changes

2024-08-31 07:08 UTC, efadeev commented
@ait-vdykyi porvalo

2024-08-31 07:31 UTC, ait-vdykyi commented
> @ait-vdykyi porvalo

I have nothing to worry about, but you do, that's why "porvalo" is rather to all those who used Russian providers and can no longer do so, and you don't worry about me) I'm fine)

2024-08-31 07:56 UTC, 3579km commented
Remove russian providers due to spread of terrorism. If they need such services they could develop their own.

2024-08-31 08:15 UTC, ikaygorodov commented
> > Fantastic first commit in a project.
> > With your help OpenTofu has made huge leap forward =)))))
> 
> Oh, thank you very much for such kind words of support, I hope your first PR for OpenTofu will also be very significant, if it ever will be of course) And thank you very much, your comment here helped everyone to understand that this PR is very important, but no matter how your comment was here, no one would have understood for sure) Well done) Once again, thank you very much) I am proud of you and I hope you are proud of yourself too)

Should I make a commit with removal of all other provideres? I gues this is the only to challenge of this PR =))))))))

2024-08-31 08:43 UTC, ait-vdykyi commented
> Should I make a commit with removal of all other provideres? I gues this is the only to challenge this PR =))))))))

How good it is to understand that a person's words in this case harm him) I hope everything will work out for you, champion)

2024-09-01 18:41 UTC, denismakogon approved these changes

2024-09-02 10:06 UTC, captainhook commented
This PR must be rejected. Why are we as open source developers causing harm to one another? Same goes for #855 and any future PR suggesting censorship in open source code/products.

It's funny that we in the West want to vilify the likes of China and Russia for censorship and oppression, while ignoring what our countries are doing to us (yes, us citizens) and the rest of the world, and wanting to commit changes like this to open source code.

To date, [OpenTofu is licensed under Mozilla Public License 2.0](https://github.com/opentofu/opentofu/blob/cb2e9119aa75eeb8e1fa175e2b7a205a4fef129f/LICENSE) and as per [Linux Foundation's website](https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects):
> What kind of open source projects are not subject to the EAR and export restrictions?
> All of them. Open source software from the Linux Foundation and project communities we work with is published and made available to the public without restrictions on further dissemination or distribution of the software.

2024-09-02 10:15 UTC, Crandel commented
> censorship and oppression

Please educate yourself about difference between censorship and sanctions against terrorist organizations. Your manipulation is not working anymore

2024-09-02 10:17 UTC, artemvang approved these changes

2024-09-02 10:19 UTC, gecube commented
@Crandel please go somewhere else. Like: vote for the removal of information about nuclear power from Wikipedia, because otherwise Iranian and North Korean you-said-terrorists will learn it and build nuclear weapon.
Your comments here is absolutely non productive, unfortunately.

2024-09-02 10:22 UTC, Crandel commented
> vote for the removal of information about nuclear power from Wikipedia, because otherwise Iranian and North Korean you-said-terrorists will learn it and build nuclear weapon, of course, to use it against you.

Your manipulation is not working anymore.

2024-09-02 10:26 UTC, ait-vdykyi commented
> This PR must be rejected. Why are we as open source developers causing harm to one another? Same goes for #855 and any future PR suggesting censorship in open source code/products.
> 
> It's funny that we in the West want to vilify the likes of China and Russia for censorship and oppression, while ignoring what our countries are doing to us (yes, us citizens) and the rest of the world, and wanting to commit changes like this to open source code.
> 
> To date, [OpenTofu is licensed under Mozilla Public License 2.0](https://github.com/opentofu/opentofu/blob/cb2e9119aa75eeb8e1fa175e2b7a205a4fef129f/LICENSE) and as per [Linux Foundation's website](https://www.linuxfoundation.org/resources/publications/understanding-us-export-controls-with-open-source-projects):
> 
> > What kind of open source projects are not subject to the EAR and export restrictions?
> > All of them. Open source software from the Linux Foundation and project communities we work with is published and made available to the public without restrictions on further dissemination or distribution of the software.
> > The following typical scenarios (but not an exhaustive list) are not subject to the EAR because “open source” is “published”:
> > 
> > * Open source software that is published publicly is not subject to the EAR
> > * Open source specifications that are published publicly are not subject to the EAR
> > * Open source files that describe the designs for hardware that are published publicly are not subject to the EAR
> > * Open source software binaries that are published publicly are not subject to the EAR
> > 
> > To meet the requirement of “published” under the EAR, however, open source communities may need to take an additional step if the project includes encryption technology.

Just for the info here is what EAR....

https://en.wikipedia.org/wiki/Export_Administration_Regulations

And now let's think. Open source programs are not subject to the EAR by policy, and therefore Russian providers subject to sanctions cannot be removed from them. Why export control at all? Typical manipulation, like see how many letters)

2024-09-02 10:46 UTC, admito88 commented
> @Crandel please go somewhere else. Like: vote for the removal of information about nuclear power from Wikipedia, because otherwise Iranian and North Korean you-said-terrorists will learn it and build nuclear weapon, of course, to use it against you. Your comments here is absolutely non productive, unfortunately.

You just wrote about the need to remove data about nuclear energy from Wikipedia because it can create problems with the proliferation of nuclear weapons and then said that the comments here are not productive) You said this in one comment) Together) Boy, your thoughts should definitely be listened to. And again, no arguments, only attempts at manipulation.

2024-09-02 11:16 UTC, dmikushin commented
A word from Russian to all Russian co-fellows:

Есть большая разница между словами "open", "neutral" и "responsibility". Даже в рамках открытого проекта разработчики могут явно выразить свою позицию путём запрета использования своего труда неприемлемым для них образом. Открытый код - это не только дар, но договор об ответственном применении. Приносить косвенную выгоду стороне, намеренно наносящей ущерб не является ответственным применением.

Но главное что мы должны понять: слова давно перестали быть достаточном выражением мыслей в этой конфронтации. Когда вам пытаются объяснить в чём вы не правы, аргументация звучит слабее, чем мысли этого человека у него в голове. Когда вы парируете и ловите человка на словах, вы понимаете, что он НА САМОМ ДЕЛЕ думает и почему. Простой пример: банки закрывают нам счета, называя какую-то бессмысленную причину. Какой смысл разбираться в причине, если причина полностью ЯСНА? Мы сами всё прекрасно понимаем, но гордыня побуждает нас ссориться, обесценивать сотрудничество и opensource. Мы не станем лучше, если успешно докажем себе, что весь мир нас предал, а вся открытость - фейк. Это не так. Но если увязывать правду и ложь, явное и потаённое в одно целое, то плохое утянет за собой хорошее на дно, и мы просто будем на этом дне, разорвав все связи не только с людьми но и со своей верой в лучшее. Нужно удержать себя от этого и сфокусироваться на любом возможном сотрудничество, какое осталось.

2024-09-02 12:52 UTC, efadeev commented
@Crandel please show us terroristic organisations whose providers were deleted from this registry

2024-09-06 17:03 UTC, olexade approved these changes

2024-09-07 19:05 UTC, yaa110 commented
> @Crandel please go somewhere else. Like: vote for the removal of information about nuclear power from Wikipedia, because otherwise Iranian and North Korean you-said-terrorists will learn it and build nuclear weapon, of course, to use it against you. Your comments here is absolutely non productive, unfortunately.

@gecube  I noticed you mentioned "Iranian and North Korean you-said-terrorists" in your comment. Can you clarify how you made the connection between terrorist organizations and these nationalities? I’m trying to understand your perspective, but it seems like a generalization, and I want to make sure we're addressing the issue without perpetuating stereotypes.

2024-09-08 09:07 UTC, olexade approved these changes

2024-09-11 17:30 UTC, corpix commented
Why opensource and tech should follow sjw bullshit like this? You may just don't use this providers if you don't like them. Whats wrong with you people?

2024-09-13 16:35 UTC, kvendingoldo commented
related to https://github.com/opentofu/registry/issues/937

2024-09-15 20:14 UTC, 21h commented
> Есть большая разница между словами "open", "neutral" и "responsibility". Даже в рамках открытого проекта разработчики могут явно выразить свою позицию путём запрета использования своего труда неприемлемым для них образом.

ты это фуфло кому-нибудь другому загоняй. open значит открытый, ни больше, ни меньше. разрабы опенсорса могут сколько угодно вставать в позу, но факт в том, что абсолютно любой может форкнуть продукт и развивать его наплевав на мнение разработчиков.

2024-09-15 21:11 UTC, dmikushin commented
> open значит открытый, ни больше, ни меньше

"Открытый" - не значит, что изгои без репутации могут сколько-угодно кататься на репутации открытого проекта.

> абсолютно любой может форкнуть продукт и развивать его наплевав на мнение разработчиков

Именно это вам уже давно и следует сделать, а не ныть тут, открывая жалобу за жалобой.

2024-09-16 04:50 UTC, ikaygorodov commented
> > open значит открытый, ни больше, ни меньше
> 
> "Открытый" - не значит, что изгои без репутации могут сколько-угодно кататься на репутации открытого проекта.
> 
> > абсолютно любой может форкнуть продукт и развивать его наплевав на мнение разработчиков
> 
> Именно это вам уже давно и следует сделать, а не ныть тут, открывая жалобу за жалобой.
> 

Причём тут нытьё, если проект нарушил не только то что изначально декларировал, но и все правила Linux Foundation и манифесты opensource. Открывающие жалобы банально призывают мейнтенеров прийти в себя дыба не угробить проект окончательно.

2024-09-16 08:04 UTC, dmikushin commented
Просто представьте себя на месте автора из Украины. Ваши знакомые убивают его знакомых, а он должен подчиниться правилам, обязывающим его сотрудничать со своими мучителями. Как тут вообще можно тыкать в какие-то правила? Я не верю что вы такие наивные или прикидываетесь шлангами. Чтобы так строить аргументацию, нужно по-настоящему быть извергами.

2024-09-16 08:07 UTC, Crandel commented
> все правила Linux Foundation и манифесты opensource.

В правилах и манифестах нигде не указано, что нужно сотрудничать с террористами и убицами. Хватит строить из себя жертву, это жалко и противно

2024-09-16 08:11 UTC, efadeev commented
> террористами и убицами

Это у каких террористов были удалены провайдеры? Просто покажи решение суда какой-нибудь страны, в котором написано, что Сбер и Яндекс - террористические организации

2024-09-16 08:42 UTC, dmikushin commented
@efadeev , в вашей картине мира сушествует только то, о чём вам выписана справка. Когда @Crandel говорит вам, что вы сотрудничаете с убийцами и террористами, он имеет в виду фактическую действительность массированных неизбирательных атак на мирное население. Вы хотите получить фотографии разбитых жилых многоэтажек Днепра и Харькова за подписью директора Linux Foundation?

2024-09-16 08:45 UTC, corpix commented
@dmikushin братан, ну давай по такой логике и Украинские хостинги выпилим, тебе атаки неизбирательным оружием по Белгородской и Курской областям показать? Или стрелочка не поворачивается? Политика в опенсорсе это скользкая дорожка

2024-09-16 08:47 UTC, Crandel commented
> Или стрелочка не поворачивается?

Убирайтесь с Украины и не будет никаких атак. Так поворачивается?

2024-09-16 08:49 UTC, Crandel commented
@cam72cam There are a lot of comments, not related to the topic, please lock this conversation too.

2024-09-16 08:53 UTC, corpix commented
«О нет, здесь говорят неудобные вещи. Скорее закройте обсуждение». Лол

2024-09-16 08:54 UTC, dmikushin commented
@corpix , Украина имеет полное право защищать себя от нападения военными средствами. Граждане Украины и других стран мира прибавляют к этому отказ от сотрудничествами с вами в сфере IT. Этот обмен репликами идёт уже долго, но вы никак не можете понять проблему. У вас не получается, может получится в будущем. Не тратье зря время, оставьте это и забудьте про OpenTofu.

2024-09-16 08:58 UTC, corpix commented
@dmikushin но военными преступлениями их удары по Белгородской и Курской области от этого быть не перестают. Выходит они тоже террористы и убийцы. И к чему мы придем с такой логикой? Что проще все удалить все что связанно с Россией и Украиной? Наверное это очень поможет остановить войну (нет, напротив, это только выставит Украину в невыгодном свете)

2024-09-16 09:01 UTC, dmikushin commented
@corpix, вы со своей стороны можете удалить всё что хотите, в соответствие со своей картиной мира. Лучше всего, если вы начнёте с удаления себя от этих обсуждений до лучших времён.

2024-09-16 09:05 UTC, efadeev commented
@corpix ты не понимаешь, армия России использует opentofu с провайдером Яндекса для запуска ракет и дронов, это же всем известно)

2024-09-16 09:06 UTC, corpix commented
@dmikushin ваше мнение очень ценно для нас. Но к счастью я выбираю путь увеличения издержек для решений, которые могут повредить сообществу

2024-09-16 09:06 UTC, Crandel commented
> Но к счастью я выбираю путь увеличения издержек для решений, которые могут повредить сообществу

А вашн мнение совершенно не ценно для нас

2024-09-16 09:57 UTC, kvendingoldo commented
Btw. If we are really talk about the politics here, the idea above is brilliant - let’s delete everything related to Russia and Ukraine, rewrite rules (say that it’s not open anymore) and block the registry from both countries. Isn’t it a plan?

2024-09-16 10:00 UTC, Crandel commented
> Russia and Ukraine, rewrite rules (say that it’s not open anymore) and block the registry from both countries.

Nobody cares about terrorist suggestions

2024-09-16 10:07 UTC, gecube commented
@Crandel Please stop labelling anybody. You know nobody who replies you and vice-versa. I don't know what is worse - to discuss some abstract things or to label people based on their names/github nicks and/or colour of passport.

2024-09-16 10:08 UTC, kvendingoldo commented
@Crandel Can we see the proof from your side that anybody from this thread is? Can we see a proof that you aren’t?

2024-09-16 10:11 UTC, gecube commented
@yaa110 please don't take it seriously, it was just hyperbole, a thing that shows that how absurd the position of somebody could be in case if it's non-consistent and it contradicts itself.

2024-09-16 10:12 UTC, dmikushin commented
@kvendingoldo, the idea is that any good open technology is potentially a weapon, and the community is responsible for preventing its misuse. What is considered a "misuse" may vary, but naturally any developer won't his work turned against him. I hope you can see that this setting is fundamentally different from government-imposed trade restrictions: you as individual want to stand away from the potential harm done using your own work against your will.

2024-09-16 10:14 UTC, kvendingoldo commented
It’s really said that OpenTofu decided to continue this conflict, and continue to loose trust points, because the official request (https://github.com/opentofu/registry/issues/937 ) for them is still unanswered and looks like that they want to skip it.

OpenTofu still didn’t any rules about deletion or additional providers to registry. It means that previous merged PR was illegal and based on the emotions. It means, that until these rules will be made, this PR is the same

2024-09-16 10:18 UTC, Crandel commented
> Please stop labelling anybody. You know nobody who replies you and vice-versa. I don't know what is worse - to discuss some abstract things or to label people based on their names/github nicks and/or colour of passport.

I don't label anyone based on passport or color. If a person compares both the attacker and the victim, it only means that he is on the side of the attacker.

2024-09-16 10:24 UTC, kvendingoldo commented
As usual, OpenTofu team started censorship instead of any answers :)

2024-09-16 11:04 UTC, dmikushin commented
Regarding censorship it would be fair to mention all Russian residents are obliged to comply with the war censorship law in force since 2022. There spread of this law onto the Russian citizens worldwide is being probed also. It means the argumentation of those exposed to this law cannot legally contradict with the official information about the military conflict. Little by little, they get used to live with it, eventually developing a specific viewpoint. Trust me: all what you could not say is also heard. Let's end here, and continue later, when it's more appropriate.

2024-09-23 00:16 UTC, kvendingoldo commented
Up. All of us are still waiting for the response (more than 2 weeks) in the issue https://github.com/opentofu/registry/issues/937 from the maintainers.

2025-02-18 02:39 UTC, divStar commented
What about software engineers, who speak Russian and use e.g. mail.ru (rather than google), because they naturally don't trust the US any more than they trust Europe, Russia or China? Are you going to exclude them, too? Jeez... guess American-lead "open source" is a joke nowadays :/

2025-02-19 09:36 UTC, olexade approved these changes

2025-02-19 09:47 UTC, admito88 commented
> What about software engineers, who speak Russian and use e.g. mail.ru (rather than google), because they naturally don't trust the US any more than they trust Europe, Russia or China? Are you going to exclude them, too? Jeez... guess American-lead "open source" is a joke nowadays :/ and obviously stupid ideology and politics wins over actual benefits from software. P.s.: I am _not_ from Russia nor am I Russian. If anything - I was born in Ukraine, but in contrast to many western people I am thinking for myself and don't care about what the political circus in any country says unless I have to. Stop getting indoctrinated by hatred and think for yourself.
> 
> And just btw: has hashicorp / Terraform considered the same fascism based on origin? If not, I should switch.

One more manipulation)

https://en.wikipedia.org/wiki/Whataboutism

2025-02-19 11:29 UTC, divStar requested changes
One would have to exclude all those people, who might use that email, but do not live in Russia. Though to be honest I do not understand how anything can call itself open-source, yet discriminate against people based on their origin.

2025-02-20 15:46 UTC, admito88 commented
> One would have to exclude all those people, who might use that email, but do not live in Russia

You said

> I am not from Russia nor am I Russian

So exclude yourself)))

2025-02-20 16:43 UTC, divStar commented
> > One would have to exclude all those people, who might use that email, but do not live in Russia
> 
> You said
> 
> > I am not from Russia nor am I Russian
> 
> So exclude yourself)))

Why are you so kneen on banning someone? Who hurt you?

2025-02-20 18:26 UTC, admito88 commented
> Why are you so kneen on banning someone? Who hurt you? Is banning someone your understanding of how a democracy is supposed to work? Sounds like some leftist Democrat sht to me...

Your words here
> One would have to exclude all those people, who might use that email, but do not live in Russia

And your words here
> I am not from Russia nor am I Russian

And now your words)))))) 
> Why are you so kneen on banning someone? 

Continue please, it's so funny))) And very instructive

2025-04-14 21:53 UTC, openuuuser commented
Hi OpenTofu maintainers,
Do you have any news about this MR? When are you going to return Yandex or do anything with this MR?
Thanks.

2026-02-09 10:57 UTC, Yantrio commented
We, The OpenTofu team, updated our policy to discuss what our stance is on accepting providers and modules here: https://github.com/opentofu/registry/blob/main/POLICY.md#provider-and-module-submission

Due to inactivity in this area and the policy upstanding for some time now I'll be closing and locking this and others related to it. Thank you

2026-02-09 10:57 UTC, closed without merging