Delete providers/s/selectel/selectel.json
opentofu/registry pull request #855
Opened 2024-08-31 12:22 UTC by rusik69

2024-08-31 13:00 UTC, gecube commented
bad work. You still miss a lot of Russian providers like @Crandel in #825. 

/sarcasm/

2024-08-31 13:29 UTC, rusik69 commented
> bad work. You still miss a lot of Russian providers like @Crandel in #825.
> 
> /sarcasm/

it was based on your comment about selectel, to be honest i only know a few russian providers

2024-08-31 14:15 UTC, efadeev commented
Sick people have no rest...

2024-08-31 14:27 UTC, konstantin90s commented
> > bad work. You still miss a lot of Russian providers like @Crandel in #825.
> > /sarcasm/
> 
> it was based on your comment about selectel, to be honest i only know a few russian providers

Boromir would've found more

2024-09-01 16:39 UTC, 21h commented
oh, open source community driven by rules. what your country? france? britain? belgium? lets remove all their providers for africans victims of their agression. usa? lets remove all their providers for mid-east countries and afganistan. israel? lets remove all their providers for palestinian victims. ukraine? lets remove all their providers for all donbas victims and terrorism in russia.

2024-09-01 18:31 UTC, 21h commented
you cant do it because you accepted cncf code of conduct 

https://github.com/cncf/foundation/blob/main/code-of-conduct.md

The CNCF Community is open, inclusive and respectful. Every member of our community has the right to have their identity respected.

Examples of behavior that contributes to a positive environment include but are not limited to:

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences

2024-09-01 19:03 UTC, rusik69 commented
> you cant do it because you all here accepted cncf code of conduct
> 
> https://github.com/cncf/foundation/blob/main/code-of-conduct.md
> 
> The CNCF Community is open, inclusive and respectful. Every member of our community has the right to have their identity respected.
> 
> Examples of behavior that contributes to a positive environment include but are not limited to:
> 
> Demonstrating empathy and kindness toward other people Being respectful of differing opinions, viewpoints, and experiences

sorry, i don't see how i disrespect your identity.

2024-09-01 19:15 UTC, 21h commented
> sorry, i don't see how i disrespect your identity.

your want do delete all russian providers. that's discrimination by nationality.

2024-09-01 19:19 UTC, Crandel commented
> your want do delete all russian providers. that's discrimination by nationality.

Poor man, you desperately need to educate yourself.

2024-09-01 19:20 UTC, rusik69 commented
> > sorry, i don't see how i disrespect your identity.
> 
> your want do delete all russian providers. that's discrimination by nationality.

can you please point me where did i say that?

2024-09-01 19:24 UTC, 21h commented
> can you please point me where did i say that?

you marked only russian providers and removing them in this pr. this is discrimination by nationality.



> Poor man, you desperately need to educate yourself.

i identify myself as russian. cncf forbids you to discriminate my identity.

2024-09-01 19:28 UTC, rusik69 commented
> > can you please point me where did i say that?
> 
> you marked only russian providers and removing them in this pr. this is discrimination by nationality.
> 
> > Poor man, you desperately need to educate yourself.
> 
> i identify myself as russian. cncf forbids you to discriminate my identity.

I've removed only one specific provider, not all russian providers

2024-09-01 19:29 UTC, 21h commented
> I've removed only one specific provider, not all russian providers

yes, with another guy here who also removing them. you both hate and discriminate russians.

2024-09-01 19:31 UTC, rusik69 commented
> > I've removed only one specific provider, not all russian providers
> 
> yes, with another guy here who also removing them. you both hate and discriminate russians.

with whom? i've never used or committed to opentofu before, and i've only seen @gecube online before.

2024-09-01 19:53 UTC, 21h commented
> with whom? i've never used or committed to opentofu before, and i've only seen @gecube online before.

with @Crandel 

you never used or committed opentofu before and came here just to remove russian provider? yes? that is not hate? just came to remove russian provider.

2024-09-01 20:02 UTC, rusik69 commented
> > with whom? i've never used or committed to opentofu before, and i've only seen @gecube online before.
> 
> with @Crandel
> 
> you never used or committed opentofu before and came here just to remove russian provider? yes? that is not hate? just came to remove russian provider.

I could be hating russians, or trying to show how stupid is removing all russian providers, or just trying to troll you all. There are many possibilities, and you don't know which one is true.

2024-09-01 20:19 UTC, kvendingoldo commented
@rusik69 so, why opentofu maintainers close PR with deletion of Google or other providers, and don't close this one? You know the answer :)

2024-09-01 20:26 UTC, rusik69 commented
> @rusik69 so, why opentofu maintainers close PRs with deletion of Google or other providers (e.g.: #826), and don't close this one? You know the answer, @21h gave a link related to that.

I'm not an opentofu maintainer, and i can't speak for them. I'm a different person, and i can have a different reason for this pr

2024-09-01 21:21 UTC, kvendingoldo commented
@rusik69 you can play in this game as much long as you can, but all people understand reasons. If this PR will be accepted, CNCF rules will be broken, that mean that OpenTofu must be excluded from it.

2024-09-01 21:26 UTC, ait-vdykyi commented
> you cant do it because you all here accepted cncf code of conduct

This is just your opinion, why don’t you say that creating a PR is not removing the provider, in fact the decision is made for you and if it is accepted positively only then the PR can be merged, so your claim should be to the project itself and not to a specific person who created this request, so you violate the CNCF. This is a personal opinion and the right to create or delete it, and the expression "you can't because" is manipulation, each person makes a decision for himself

> your want do delete all russian providers. that's discrimination by nationality.

You are lying, in this PR only one provider is deleted, not all, hyperbolizing the event is also manipulation

> yes, with another guy here who also removing them. you both hate and discriminate russians.

Another lie, where exactly in this request or from the people who created it are there words about open hatred for Russians? This is again manipulation and creating pressure on a person. Maybe they do it out of great love, how do you know?)

> you never used or committed opentofu before and came here just to remove russian provider? yes? that is not hate? just came to remove russian provider.

A lot of questions in a short period of time is also pressure and manipulation... Are you from propaganda or from the Russian security forces? Do you have a car? And if there is, which one? How do you feel about Ukrainians? Do you have relatives from Western Europe?)))

2024-09-01 21:30 UTC, kvendingoldo commented
@cam72cam @DicsyDel @Yantrio  pls, delete the last comment from @ait-vdykyi he is trying to provoke aggression and hatred with his behavior

2024-09-01 21:34 UTC, rusik69 commented
> all people understand reasons

and many people prefer to "understand" only the reason they want, not the real one

2024-09-01 21:34 UTC, admito88 commented
@kvendingoldo how is your project with Yandex? I hope all is well. This PR does not contain materials of hatred against nations or ethnic groups, so you can read the CNCF even to the letter, good luck comparing them with the reasons of people creating these PRs and also somehow combining them with sanctions from America and the European Union. It's just an attempt to put pressure on a person...

2024-09-01 21:37 UTC, kvendingoldo commented
@admitto why do you ask? Do you want to get a lesson about project with a true open source rules that don't oppes anybody ? :)

2024-09-01 21:41 UTC, admito88 commented
> @admitto why do you ask? Do you want to get a lesson about project with a true open source rules that don't oppes anybody ? :)

Definitely not from you, I do not have such a high level of concern for Kazakhstan as you do, so nothing will work)

2024-09-01 21:46 UTC, admito88 commented
@cam72cam @DicsyDel @Yantrio Please consider closing the comments on this PR because @kvendingoldo and @21h in my opinion are deliberately putting psychological pressure on @rusik69 to prevent him from making his own decision.

2024-09-01 22:16 UTC, kvendingoldo commented
@admito88 any proof, please? I see only your involvement to this PR for being merged.

2024-09-01 22:18 UTC, kvendingoldo commented
> Definitely not from you, I do not have such a high level of concern for Kazakhstan as you do, so nothing will work)

I don't have it either. I have concern only about opensource rules, that ppl should follow.

2024-09-02 07:38 UTC, he0s requested changes
It's unclear why this provider should be removed. It's a good practice in the open source world when you provide all necessary information on reason why any changes should be made.

2024-09-02 07:46 UTC, gecube requested changes
no justification

2024-09-02 19:42 UTC, kvendingoldo requested changes
No justification.

2024-09-02 19:45 UTC, Crandel approved these changes

2024-09-02 20:33 UTC, 21h commented
few ukrainian guys tries to remove russian providers. so what the reason? can you tell us?

2024-09-02 20:39 UTC, rusik69 commented
> few ukrainian guys tries to remove russian providers. so what the reason? can you tell us?

sorry to disappoint you, but i'm not ukrainian

2024-09-03 15:27 UTC, vhlukhov approved these changes

2024-09-08 09:45 UTC, olexade approved these changes

2024-09-13 16:34 UTC, kvendingoldo commented
related to https://github.com/opentofu/registry/issues/937

2024-09-14 19:01 UTC, 21h commented
> Чья бы корова мычала. Терористам не место в цивилизованном мире!

так убирайтесь из курской области, прекратите обстреливать мирные русские города, вы убийцы мирных людей и террористы, вам не место в цивилизованном мире.

2024-09-23 00:16 UTC, kvendingoldo commented
Up. All of us are still waiting for the response (more than 2 weeks) in the issue https://github.com/opentofu/registry/issues/937 from the maintainers.

2025-04-14 21:58 UTC, openuuuser commented
Any news here? Can maintainers finally reject it?

2026-02-09 10:58 UTC, Yantrio commented
We, The OpenTofu team, updated our policy to discuss what our stance is on accepting providers and modules here: https://github.com/opentofu/registry/blob/main/POLICY.md#provider-and-module-submission

Due to inactivity in this area and the policy upstanding for some time now I'll be closing and locking this and others related to it. Thank you

2026-02-09 10:58 UTC, closed without merging